apiVersion: apps/v1
kind: Deployment
metadata:
  name: yess
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yess
  template:
    metadata:
      labels:
        app: yess
    spec:
      containers:
      - image: okteto.dev/ray:latest
        name: yess
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "f3931d70-fc84-4a95-bfa6-a14261a6a7f5"
        - name: Vless_Path
          value: "/app"
        - name: Vmess_UUID
          value: "f3931d70-fc84-4a95-bfa6-a14261a6a7f5"
        - name: Vmess_Path
          value: "/add"
        - name: Share_Path
          value: "/share233"
